#!/usr/bin/env python3
"""BroWatch i18n stage 1: inventory of user-visible string literals.

Scans src/ui_*.cpp, src/squachy.cpp, src/detection_info.cpp,
src/signatures.cpp, src/settings.cpp, src/meshtalk.cpp, src/meshtutor.cpp,
src/emote_script.cpp, src/qwerty.cpp and reports every C string literal
with file:line. Output: tools/strings_inventory.txt

This changes nothing in the build -- it is the map for stage 2
(include/strings_en.h + strings_ru.h + Settings::lang switch).
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src")

FILES = sorted(
    f for f in os.listdir(SRC)
    if (f.startswith("ui_") or f in (
        "squachy.cpp", "detection_info.cpp", "signatures.cpp",
        "settings.cpp", "meshtalk.cpp", "meshtutor.cpp",
        "emote_script.cpp", "qwerty.cpp", "meshwords.cpp",
        "clock.cpp", "security.cpp", "bingo.cpp", "idle_events.cpp",
    )) and f.endswith(".cpp")
)

# "..." with escapes, single-line only (UI strings are single-line).
STR = re.compile(r'"((?:[^"\\\n]|\\.)*)"')

SKIP_PREFIX = ("[",)  # serial tags like "[clock]" are still listed; prefix kept for grep


def main():
    out = []
    total = 0
    for f in FILES:
        path = os.path.join(SRC, f)
        with open(path, encoding="utf-8", errors="replace") as fh:
            for n, line in enumerate(fh, 1):
                for m in STR.finditer(line):
                    s = m.group(1)
                    if not s:
                        continue
                    out.append("%s:%d: \"%s\"" % (f, n, s))
                    total += 1
    inv = os.path.join(ROOT, "tools", "strings_inventory.txt")
    with open(inv, "w", encoding="utf-8") as fh:
        fh.write("# BroWatch string inventory: %d literals in %d files\n" % (total, len(FILES)))
        fh.write("# Generated by tools/extract_strings.py -- do not hand-edit.\n")
        fh.write("\n".join(out) + "\n")
    print("files: %d, literals: %d -> %s" % (len(FILES), total, inv))


if __name__ == "__main__":
    sys.exit(main())
